[package]
name = "prose"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
